### ISSUE TITLE
Замечания по 1 лабе

### ISSUE THREAD

**Issue by veresnikov** [deniko192/web_dev#1]
1. Точно ли нужно было комитить директорию data? Думаю можно не комитить
2. Напрямую читать из переменной $_GET не очень хорошо
3. RequestSurveyLoader сейчас работает не понятно. Функция createSurvey сама берет данные из запроса и создает объект Survey. Думаю лучше сделать для класса конструктор, где будет приходить массив параметров и записать их в приватное поле, а функцию createSurvey переименовать и вытащить данные уже из приватного поля
4. [Думаю сразу понятно](https://www.google.com/url?sa=i&url=https%3A%2F%2Fpikabu.ru%2Fstory%2Fyumor_programmista_3722398&psig=AOvVaw2HWCJIrqqJdWjGgBqhQJJh&ust=1648756109098000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPiI5MD17vYCFQAAAAAdAAAAABAD)
5. Разве email у Survey может быть null?
6. `$value = explode(self::SEPARATOR, $line, 2);` почему именно 2?, магических чисел стоит избегать
7. createFileName думаю можно назвать getFullPatch, или что то в этом духе
8. В целом, SurveyFileStorage можно тоже сделать конструктор и конфигурировать его из вне, тогда при изменении директории или разделителя, не придется лезть в реализацию класса

**Comment by deniko192** [comment]
> 2\. Напрямую читать из переменной $_GET не очень хорошо

Есть альтернативы?


> 5\. Разве email у Survey может быть null?

Почему нет? В условии задачи вроде не запрещено, в реализации этот случай обрабатывается

**Comment by deniko192** [comment]
Все правки:
https://github.com/deniko192/web_dev/commit/a11767b2e9fac93c6cf4d32240d7f9707011e8a0

**Comment by veresnikov** [comment]
2. Конечно. Вам на лекциях давали пример функции getGetParameter, которая скрывает использование глобальной переменной внутри себя. Так можно будет в случае необходимости подменить реализацию функции, не меняя места использования кода
3. Выглядит не очень логично. Мы знаем какие поля могут опциональны, а какие нет. И поле email может выступать например в роли логина, но ведь у пользователя всегда он есть. В дальнейшем кто то может использовать класс Survey, но не посмотреть что нужно обработать ситуацию с пустым email

**Comment by deniko192** [comment]
Поправил:
https://github.com/deniko192/web_dev/commit/b0b4f2601a363909f0739789c50e1a2a850f1636
https://github.com/deniko192/web_dev/commit/bcbe3a803cb1b41811e21ea97751e7aab0feaaef
https://github.com/deniko192/web_dev/commit/47f339dc7c3ce0ed11376af7811f747ccd1dfcd4
