### ISSUE TITLE
2 лаба

### ISSUE THREAD

**Issue by veresnikov** [deniko192/web_dev#2]
https://github.com/deniko192/web_dev/blob/4fc88a7ce4ce8e978ce5d1c0c6806e3937942123/lw2/config/routes.yaml#L3
можно объединить в один контроллер 

Убрать неиспользуемые файлы и директории, если есть ошибки при удалении директории стоит посмотреть конфиги

Сейчас контроллер реализует слишком много логики, для этого стоит выделить некий сервис

**Comment by deniko192** [comment]
Поправил

**Comment by veresnikov** [comment]
Нормас, осталось немного

В saveSurvey скорее имеет место кидать exception в случае ошибки
Интерфейс для Survey избыточен

**Comment by deniko192** [comment]
Поправил
